### ISSUE TITLE
"Type" of onchart data seems to affect display

### ISSUE THREAD

**Issue by svezina** [C451/trading-vue-js#2]
Hi,
If I create an "onchart" or "offchart" element in my data, the "type" var seems to break if it's not a specific thing.

This will work:
```
{
"name": "EMA, 75",
"type": "EMA",
"data": my_data,
"settings": {}
},
```

but this will not:

```
{
"name": "EMA, 75",
"type": "Hello",
"data": my_data,
"settings": {}
},
```

Is this a feature or a bug?  In the meantime I'm leaving EMA for all my onchart lines and RSI for all of my offchart lines and it works.
Thanks

**Comment by C451** [comment]
Hi, 
That's expected because we have only two types of built-in indicators: 'Spline' (EMA is a spline) and 'RSI'. 

Use generic type 'Spline' for all line-based stuff. Also look here https://github.com/C451/trading-vue-js/blob/master/src/components/overlays/Spline.vue  

` use_for() { return ['Spline', 'EMA', 'SMA'] },`

Docs are coming.

**Comment by C451** [comment]
Added 'Unknown type' warning for this case.
