### ISSUE TITLE
How to remove gaps between candles 

### ISSUE THREAD

**Issue by khyoz** [C451/trading-vue-js#36]
First, amazing, very good job already !
Are there some options or solutions to remove gaps when we display daily candles ?

![2bug-tradevue-2019-07-16_165015](https://user-images.githubusercontent.com/26684951/61304938-3ed76480-a7ea-11e9-984d-e4c55ce24233.png)

**Comment by C451** [comment]
Thanks!

Yeah, I'm fully aware of this problem, but so far there is no simple solution. I need to rethink the grid calculation algo (where things can become complicated due to different time warps). As you can see, now the library uses a rather dumb method (t % INTERVAL === 0): 

https://github.com/C451/trading-vue-js/blob/master/src/components/js/grid_maker.js#L160

I hope to fix this in the foreseeable future.

**Comment by C451** [comment]
Basically, the same:  https://github.com/C451/trading-vue-js/issues/17#issuecomment-487184922

**Comment by msincenselee** [comment]
suggestion: use lable replace timestamp as x axis
